language: python
python:
  - "3.5"
# command to install dependencies

install:
  - pip install coverage
  - pip install coveralls
  - pip install .

script:
  coverage run ituneslibrarian search -f aaa

after_success:
  coveralls

branches:
  only:
    - master
