language: python
python:
  - "3.5"
# command to install dependencies

install:
  pip install coverage
  pip install coveralls

script:
  coverage run ituneslibrarian

after_success:
  coveralls

branches:
  only:
    - master
